import os

import psycopg2
from psycopg2 import Error

try:
    connection = psycopg2.connect(user='postgres',
                                  password=os.getenv('POSTGRESQL_PASSWORD'),
                                  database='vk_messages',
                                  host='127.0.0.1',
                                  port=5432)
    cursor = connection.cursor()
    cursor.execute('CREATE TABLE IF NOT EXISTS users ('
                   '    vk_id INT PRIMARY KEY,'
                   '    vk_url_nickname VARCHAR(50) UNIQUE NOT NULL,'
                   '    vk_first_name VARCHAR(50) NOT NULL,'
                   '    vk_last_name VARCHAR(50) NOT NULL'
                   ');'
                   'CREATE TABLE IF NOT EXISTS messages ('
                   '    id INT PRIMARY KEY,'
                   '    date TIMESTAMP NOT NULL,'
                   '    from_id INT NOT NULL,'
                   '    text TEXT,'
                   '    FOREIGN KEY (from_id) REFERENCES users (vk_id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS photos ('
                   '    message_id INT NOT NULL,'
                   '    url TEXT NOT NULL,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS stickers ('
                   '    message_id INT NOT NULL UNIQUE,'
                   '    product_id INT NOT NULL,'
                   '    sticker_id INT NOT NULL,'
                   '    url_image VARCHAR(50) NOT NULL,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS links ('
                   '    message_id INT NOT NULL,'
                   '    title TEXT,'
                   '    url TEXT NOT NULL,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS videos ('
                   '    message_id INT NOT NULL,'
                   '    description TEXT,'
                   '    duration INT NOT NULL,'
                   '    image_url TEXT,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS docs ('
                   '    message_id INT NOT NULL,'
                   '    title VARCHAR(255),'
                   '    extension VARCHAR(255),'
                   '    url TEXT,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS audios ('
                   '    message_id INT NOT NULL,'
                   '    artist VARCHAR(255) NOT NULL,'
                   '    title VARCHAR(255) NOT NULL,'
                   '    duration INT NOT NULL,'
                   '    url TEXT,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS audio_messages ('
                   '    message_id INT NOT NULL UNIQUE,'
                   '    duration INT NOT NULL,'
                   '    link_ogg VARCHAR(255) NOT NULL UNIQUE,'
                   '    link_mp3 VARCHAR(255) NOT NULL UNIQUE,'
                   '    transcription TEXT,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS calls ('
                   '    message_id INT NOT NULL UNIQUE,'
                   '    initiator_id INT NOT NULL,'
                   '    state VARCHAR(60) NOT NULL,'
                   '    video BOOLEAN NOT NULL,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id),'
                   '    FOREIGN KEY (initiator_id) REFERENCES users (vk_id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS gifts ('
                   '    message_id INT NOT NULL UNIQUE,'
                   '    gift_id INT NOT NULL,'
                   '    gift_image VARCHAR(255) NOT NULL,'
                   '    stickers_product_id INT,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS walls ('
                   '    message_id INT NOT NULL UNIQUE,'
                   '    post_date TIMESTAMP,'
                   '    post_type VARCHAR(20),'
                   '    text TEXT,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS graffiti ('
                   '    message_id INT NOT NULL UNIQUE,'
                   '    url VARCHAR(255),'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');'
                   'CREATE TABLE IF NOT EXISTS stories ('
                   '    message_id INT NOT NULL UNIQUE,'
                   '    story_date TIMESTAMP NOT NULL,'
                   '    expires_at TIMESTAMP NOT NULL,'
                   '    is_one_time BOOLEAN,'
                   '    can_see INT,'
                   '    FOREIGN KEY (message_id) REFERENCES messages (id)'
                   ');')
except (Exception, Error) as error:
    print('Ошибка при работе с PostgreSQL', error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print('Соединение с PostgreSQL закрыто')
